const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getProducts:   ()        => ipcRenderer.invoke('get-products'),
  getCustomers:  ()        => ipcRenderer.invoke('get-customers'),
  addProduct:    (product) => ipcRenderer.invoke('add-product', product),
  updateProduct: (data)    => ipcRenderer.invoke('update-product', data),
  addStockToProduct: (data)=> ipcRenderer.invoke('add-stock-to-product', data),
  deleteProduct: (id, userName) => ipcRenderer.invoke('delete-product', id, userName),
  searchProduct: (query)   => ipcRenderer.invoke('search-product', query),
  processSale:   (data)    => ipcRenderer.invoke('process-sale', data),
  getRecentSales:()        => ipcRenderer.invoke('get-recent-sales'),
  getAllSalesHistory: (opts) => ipcRenderer.invoke('get-all-sales-history', opts),
  processFullReturn:(id)   => ipcRenderer.invoke('process-full-return', id),
  processReturn: (data)    => ipcRenderer.invoke('process-return', data),
  getPrinters:   ()        => ipcRenderer.invoke('get-printers'),
  printReceipt:  (data)    => ipcRenderer.invoke('print-receipt', data),
  printLabel:    (data)    => ipcRenderer.invoke('print-label', data),
  payDebt:       (data)    => ipcRenderer.invoke('pay-debt', data),
  addManualDebt: (data)    => ipcRenderer.invoke('add-manual-debt', data),
  getReports:    (dates)   => ipcRenderer.invoke('get-reports', dates),
  getWaitersReport: (opts) => ipcRenderer.invoke('get-waiters-report', opts),
  getSalesForExcel: (dates)=> ipcRenderer.invoke('get-sales-for-excel', dates),
  getLowStock:   (limit)   => ipcRenderer.invoke('get-low-stock', limit),
  clearTestData: ()        => ipcRenderer.invoke('clear-test-data'),
  clearWarehouse: ()       => ipcRenderer.invoke('clear-warehouse'),
  resetFactoryData: ()     => ipcRenderer.invoke('reset-factory-data'),
  getCurrentShiftStats: () => ipcRenderer.invoke('get-current-shift-stats'),
  closeShift: (stats)      => ipcRenderer.invoke('close-shift', stats),
  getCustomerDebtDetails: (id) => ipcRenderer.invoke('get-customer-debt-details', id),
  verifyPin:     (pin)     => ipcRenderer.invoke('verify-pin', pin),
  maybeOpenShift: (name)   => ipcRenderer.invoke('maybe-open-shift', name),
  getSettings:   ()        => ipcRenderer.invoke('get-settings'),
  updateSetting: (data)    => ipcRenderer.invoke('update-setting', data),
  syncUsdRate:   ()        => ipcRenderer.invoke('sync-usd-rate'),
  checkBaseLoaded: ()      => ipcRenderer.invoke('check-base-loaded'),
  loadInitialBase: (type)  => ipcRenderer.invoke('load-initial-base', type),
  getRestaurantTables: ()  => ipcRenderer.invoke('get-restaurant-tables'),
  getActiveOrderForTable: (tableId) => ipcRenderer.invoke('get-active-order-for-table', tableId),
  saveRestaurantOrder: (tableId, waiterId, items) => ipcRenderer.invoke('save-restaurant-order', tableId, waiterId, items),
  closeRestaurantOrder: (data) => ipcRenderer.invoke('close-restaurant-order', data),
  closeRestaurantOrderOnly: (tableId) => ipcRenderer.invoke('close-restaurant-order-only', tableId),
  getWaiters:   ()        => ipcRenderer.invoke('get-waiters'),
  addWaiter:    (data)    => ipcRenderer.invoke('add-waiter', data),
  deleteWaiter: (id)      => ipcRenderer.invoke('delete-waiter', id),
  transferRestaurantTable: (data) => ipcRenderer.invoke('transfer-restaurant-table', data),
  transferRestaurantOrderWaiter: (data) => ipcRenderer.invoke('transfer-restaurant-order-waiter', data),
  cancelRestaurantOrder: (data) => ipcRenderer.invoke('cancel-restaurant-order', data),
  addDeliveryOrder: (data) => ipcRenderer.invoke('add-delivery-order', data),
  addRestaurantTable: (data) => ipcRenderer.invoke('add-restaurant-table', data),
  deleteRestaurantTable: (tableId) => ipcRenderer.invoke('delete-restaurant-table', tableId),
  getRestaurantZones: () => ipcRenderer.invoke('get-restaurant-zones'),
  addRestaurantZone: (name) => ipcRenderer.invoke('add-restaurant-zone', name),
  deleteRestaurantZone: (name) => ipcRenderer.invoke('delete-restaurant-zone', name),
  saveProductRecipe: (productId, ingredients) => ipcRenderer.invoke('save-product-recipe', productId, ingredients),
  getProductRecipe: (productId) => ipcRenderer.invoke('get-product-recipe', productId),
  lockTable: (tableId, userName) => ipcRenderer.invoke('lock-table', tableId, userName),
  unlockTable: (tableId, userName) => ipcRenderer.invoke('unlock-table', tableId, userName),
  setTablePrePrinted: (tableId, isPrinted) => ipcRenderer.invoke('set-table-pre-printed', tableId, isPrinted),
  getCashiers:   ()        => ipcRenderer.invoke('get-cashiers'),
  addCashier:    (data)    => {
    // support role and salary arguments
    return ipcRenderer.invoke('add-cashier', data);
  },
  deleteCashier: (id)      => ipcRenderer.invoke('delete-cashier', id),
  updateCashierPin: (data) => ipcRenderer.invoke('update-cashier-pin', data),
  exportDB:      (name)    => ipcRenderer.invoke('export-db', name),
  importDB:      ()        => ipcRenderer.invoke('import-db'),
  optimizeDatabase: ()     => ipcRenderer.invoke('optimize-database'),
  autoBackupDB:  ()        => ipcRenderer.invoke('auto-backup-db'),
  writeOffProduct: (data)  => ipcRenderer.invoke('write-off-product', data),
  getWriteOffs:  ()        => ipcRenderer.invoke('get-write-offs'),
  getInventoryLogs: (opts) => ipcRenderer.invoke('get-inventory-logs', opts),
  addExpense:    (data)    => ipcRenderer.invoke('add-expense', data),
  deleteExpense: (id)      => ipcRenderer.invoke('delete-expense', id),
  deleteCustomer: (data)   => ipcRenderer.invoke('delete-customer', data),
  getMachineId:  ()        => ipcRenderer.invoke('get-machine-id'),
  getActivation: ()        => ipcRenderer.invoke('get-activation'),
  saveActivation:(fingerprint) => ipcRenderer.invoke('save-activation', fingerprint),
  clearActivation:()       => ipcRenderer.invoke('clear-activation'),
  onMobileSalePrinted: (callback) => {
    ipcRenderer.removeAllListeners('mobile-sale-printed');
    ipcRenderer.on('mobile-sale-printed', (_, data) => callback(data));
  },
  getNgrokUrl: () => ipcRenderer.invoke('get-ngrok-url'),
  getExpressPort: () => ipcRenderer.invoke('get-express-port'),
  saveNgrokSettings: (data) => ipcRenderer.invoke('save-ngrok-settings', data),
  exportSaleExcel: (saleDetails) => ipcRenderer.invoke('export-sale-excel', saleDetails),
  printA4Invoice: (saleDetails) => ipcRenderer.invoke('print-a4-invoice', saleDetails),
  getAiInsights: () => ipcRenderer.invoke('get-ai-insights'),
  saveNetworkSettings: (data) => ipcRenderer.invoke('save-network-settings', data),
  getNetworkSettings: () => ipcRenderer.invoke('get-network-settings'),
  getLocalIPs: () => ipcRenderer.invoke('get-local-ips'),
  onNgrokUrlUpdated: (callback) => {
    ipcRenderer.removeAllListeners('ngrok-url-updated');
    ipcRenderer.on('ngrok-url-updated', (_, url) => callback(url));
  },
  onNgrokUrlSuccess: (callback) => {
    ipcRenderer.removeAllListeners('ngrok-url-success');
    ipcRenderer.on('ngrok-url-success', (_, url) => callback(url));
  },
  onNgrokUrlError: (callback) => {
    ipcRenderer.removeAllListeners('ngrok-url-error');
    ipcRenderer.on('ngrok-url-error', (_, err) => callback(err));
  },
  getProductGroups: () => ipcRenderer.invoke('get-product-groups'),
  addProductGroup: (name) => ipcRenderer.invoke('add-product-group', name),
  getAttendance: (date) => ipcRenderer.invoke('get-attendance', date),
  saveAttendance: (data) => ipcRenderer.invoke('save-attendance', data),
  updateCashier: (data) => ipcRenderer.invoke('update-cashier', data),
  updateWaiter: (data) => ipcRenderer.invoke('update-waiter', data)
});
