const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getProducts:   ()        => ipcRenderer.invoke('get-products'),
  getCustomers:  ()        => ipcRenderer.invoke('get-customers'),
  addProduct:    (product) => ipcRenderer.invoke('add-product', product),
  updateProduct: (data)    => ipcRenderer.invoke('update-product', data),
  addStockToProduct: (data)=> ipcRenderer.invoke('add-stock-to-product', data),
  deleteProduct: (id, userName) => ipcRenderer.invoke('delete-product', id, userName),
  uploadProductImage: (data) => ipcRenderer.invoke('upload-product-image', data),
  deleteProductImage: (fileName) => ipcRenderer.invoke('delete-product-image', fileName),
  toggleProductStop: (id, isStopped) => ipcRenderer.invoke('toggle-product-stop', { id, isStopped }),
  setProductStopWithLimit: (data) => ipcRenderer.invoke('set-product-stop-with-limit', data),
  searchProduct: (query)   => ipcRenderer.invoke('search-product', query),
  processSale:   (data)    => ipcRenderer.invoke('process-sale', data),
  getRecentSales:()        => ipcRenderer.invoke('get-recent-sales'),
  getAllSalesHistory: (opts) => ipcRenderer.invoke('get-all-sales-history', opts),
  processFullReturn:(id)   => ipcRenderer.invoke('process-full-return', id),
  processReturn: (data)    => ipcRenderer.invoke('process-return', data),
  getPrinters:   ()        => ipcRenderer.invoke('get-printers'),
  printReceipt:  (data)    => ipcRenderer.invoke('print-receipt', data),
  printLabel:    (data)    => ipcRenderer.invoke('print-label', data),
  payDebt:       (data)    => ipcRenderer.invoke('pay-debt', data),
  addManualDebt: (data)    => ipcRenderer.invoke('add-manual-debt', data),
  getReports:    (dates)   => ipcRenderer.invoke('get-reports', dates),
  getWaitersReport: (opts) => ipcRenderer.invoke('get-waiters-report', opts),
  getSalesForExcel: (dates)=> ipcRenderer.invoke('get-sales-for-excel', dates),
  getLowStock:   (limit)   => ipcRenderer.invoke('get-low-stock', limit),
  clearTestData: ()        => ipcRenderer.invoke('clear-test-data'),
  clearWarehouse: ()       => ipcRenderer.invoke('clear-warehouse'),
  resetFactoryData: ()     => ipcRenderer.invoke('reset-factory-data'),
  getCurrentShiftStats: () => ipcRenderer.invoke('get-current-shift-stats'),
  closeShift: (stats)      => ipcRenderer.invoke('close-shift', stats),
  getCustomerDebtDetails: (id) => ipcRenderer.invoke('get-customer-debt-details', id),
  verifyPin:     (pin)     => ipcRenderer.invoke('verify-pin', pin),
  maybeOpenShift: (name)   => ipcRenderer.invoke('maybe-open-shift', name),
  getSettings:   ()        => ipcRenderer.invoke('get-settings'),
  updateSetting: (data)    => ipcRenderer.invoke('update-setting', data),
  syncUsdRate:   ()        => ipcRenderer.invoke('sync-usd-rate'),
  checkBaseLoaded: ()      => ipcRenderer.invoke('check-base-loaded'),
  loadInitialBase: (type)  => ipcRenderer.invoke('load-initial-base', type),
  getRestaurantTables: ()  => ipcRenderer.invoke('get-restaurant-tables'),
  getActiveOrderForTable: (tableId) => ipcRenderer.invoke('get-active-order-for-table', tableId),
  saveRestaurantOrder: (tableId, waiterId, items) => ipcRenderer.invoke('save-restaurant-order', tableId, waiterId, items),
  closeRestaurantOrder: (data) => ipcRenderer.invoke('close-restaurant-order', data),
  closeRestaurantOrderOnly: (tableId) => ipcRenderer.invoke('close-restaurant-order-only', tableId),
  getWaiters:   ()        => ipcRenderer.invoke('get-waiters'),
  addWaiter:    (data)    => ipcRenderer.invoke('add-waiter', data),
  deleteWaiter: (id)      => ipcRenderer.invoke('delete-waiter', id),
  transferRestaurantTable: (data) => ipcRenderer.invoke('transfer-restaurant-table', data),
  transferRestaurantOrderWaiter: (data) => ipcRenderer.invoke('transfer-restaurant-order-waiter', data),
  cancelRestaurantOrder: (data) => ipcRenderer.invoke('cancel-restaurant-order', data),
  addDeliveryOrder: (data) => ipcRenderer.invoke('add-delivery-order', data),
  addRestaurantTable: (data) => ipcRenderer.invoke('add-restaurant-table', data),
  deleteRestaurantTable: (tableId) => ipcRenderer.invoke('delete-restaurant-table', tableId),
  getRestaurantZones: () => ipcRenderer.invoke('get-restaurant-zones'),
  addRestaurantZone: (name) => ipcRenderer.invoke('add-restaurant-zone', name),
  deleteRestaurantZone: (name) => ipcRenderer.invoke('delete-restaurant-zone', name),
  saveProductRecipe: (productId, ingredients) => ipcRenderer.invoke('save-product-recipe', productId, ingredients),
  getProductRecipe: (productId) => ipcRenderer.invoke('get-product-recipe', productId),
  produceSemiFinished: (productId, quantity, userName) => ipcRenderer.invoke('produce-semi-finished', productId, quantity, userName),
  getSubWarehouses: () => ipcRenderer.invoke('get-sub-warehouses'),
  addSubWarehouse: (name, note) => ipcRenderer.invoke('add-sub-warehouse', name, note),
  createStockTransfer: (data) => ipcRenderer.invoke('create-stock-transfer', data),
  getStockTransfers: (params) => ipcRenderer.invoke('get-stock-transfers', params),
  getDirectorStats: (period) => ipcRenderer.invoke('get-director-stats', period),
  writeOffProduct: (data) => ipcRenderer.invoke('write-off-product', data),
  getWriteOffs: (params) => ipcRenderer.invoke('get-write-offs', params),
  getSuppliers: () => ipcRenderer.invoke('get-suppliers'),
  addSupplier: (data) => ipcRenderer.invoke('add-supplier', data),
  updateSupplier: (data) => ipcRenderer.invoke('update-supplier', data),
  deleteSupplier: (id) => ipcRenderer.invoke('delete-supplier', id),
  addSupplierInvoice: (data) => ipcRenderer.invoke('add-supplier-invoice', data),
  getSupplierInvoices: (params) => ipcRenderer.invoke('get-supplier-invoices', params),
  paySupplierDebt: (data) => ipcRenderer.invoke('pay-supplier-debt', data),
  lockTable: (tableId, userName) => ipcRenderer.invoke('lock-table', tableId, userName),
  unlockTable: (tableId, userName) => ipcRenderer.invoke('unlock-table', tableId, userName),
  setTablePrePrinted: (tableId, isPrinted) => ipcRenderer.invoke('set-table-pre-printed', tableId, isPrinted),
  getCashiers:   ()        => ipcRenderer.invoke('get-cashiers'),
  addCashier:    (data)    => {
    // support role and salary arguments
    return ipcRenderer.invoke('add-cashier', data);
  },
  deleteCashier: (id)      => ipcRenderer.invoke('delete-cashier', id),
  updateCashierPin: (data) => ipcRenderer.invoke('update-cashier-pin', data),
  exportDB:      (name)    => ipcRenderer.invoke('export-db', name),
  importDB:      ()        => ipcRenderer.invoke('import-db'),
  optimizeDatabase: ()     => ipcRenderer.invoke('optimize-database'),
  autoBackupDB:  ()        => ipcRenderer.invoke('auto-backup-db'),
  sendTelegramBackup: (opts) => ipcRenderer.invoke('send-telegram-backup', opts),
  getTelegramChatId: (token) => ipcRenderer.invoke('get-telegram-chat-id', token),
  sendAttendanceTestMessage: (opts) => ipcRenderer.invoke('send-attendance-test-message', opts),
  writeOffProduct: (data)  => ipcRenderer.invoke('write-off-product', data),
  getWriteOffs:  ()        => ipcRenderer.invoke('get-write-offs'),
  getInventoryLogs: (opts) => ipcRenderer.invoke('get-inventory-logs', opts),
  addExpense:    (data)    => ipcRenderer.invoke('add-expense', data),
  deleteExpense: (id, userName) => ipcRenderer.invoke('delete-expense', id, userName),
  deleteCustomer: (data)   => ipcRenderer.invoke('delete-customer', data),
  getMachineId:  ()        => ipcRenderer.invoke('get-machine-id'),
  getActivation: ()        => ipcRenderer.invoke('get-activation'),
  saveActivation:(fingerprint) => ipcRenderer.invoke('save-activation', fingerprint),
  clearActivation:()       => ipcRenderer.invoke('clear-activation'),
  getAppVersion: ()        => ipcRenderer.invoke('get-app-version'),
  checkUpdate:   ()        => ipcRenderer.invoke('check-update'),
  startDownload: ()        => ipcRenderer.invoke('start-download'),
  installUpdate: ()        => ipcRenderer.invoke('install-update'),
  onUpdateStatus:(callback) => {
    const channels = ['checking-for-update', 'update-available', 'update-not-available', 'download-progress', 'update-downloaded', 'update-error'];
    channels.forEach(ch => {
      ipcRenderer.removeAllListeners(ch);
      ipcRenderer.on(ch, (_, data) => callback(ch, data));
    });
  },
  onMobileSalePrinted: (callback) => {
    ipcRenderer.removeAllListeners('mobile-sale-printed');
    ipcRenderer.on('mobile-sale-printed', (_, data) => callback(data));
  },
  getNgrokUrl: () => ipcRenderer.invoke('get-ngrok-url'),
  getExpressPort: () => ipcRenderer.invoke('get-express-port'),
  saveNgrokSettings: (data) => ipcRenderer.invoke('save-ngrok-settings', data),
  exportSaleExcel: (saleDetails) => ipcRenderer.invoke('export-sale-excel', saleDetails),
  printA4Invoice: (saleDetails) => ipcRenderer.invoke('print-a4-invoice', saleDetails),
  getAiInsights: () => ipcRenderer.invoke('get-ai-insights'),
  saveNetworkSettings: (data) => ipcRenderer.invoke('save-network-settings', data),
  getNetworkSettings: () => ipcRenderer.invoke('get-network-settings'),
  getLocalIPs: () => ipcRenderer.invoke('get-local-ips'),
  onNgrokUrlUpdated: (callback) => {
    ipcRenderer.removeAllListeners('ngrok-url-updated');
    ipcRenderer.on('ngrok-url-updated', (_, url) => callback(url));
  },
  onNgrokUrlSuccess: (callback) => {
    ipcRenderer.removeAllListeners('ngrok-url-success');
    ipcRenderer.on('ngrok-url-success', (_, url) => callback(url));
  },
  onNgrokUrlError: (callback) => {
    ipcRenderer.removeAllListeners('ngrok-url-error');
    ipcRenderer.on('ngrok-url-error', (_, err) => callback(err));
  },
  getProductGroups: () => ipcRenderer.invoke('get-product-groups'),
  addProductGroup: (name) => ipcRenderer.invoke('add-product-group', name),
  getAttendance: (date) => ipcRenderer.invoke('get-attendance', date),
  saveAttendance: (data) => ipcRenderer.invoke('save-attendance', data),
  getAttendanceReport: (params) => ipcRenderer.invoke('get-attendance-report', params),
  saveManualAttendance: (data) => ipcRenderer.invoke('save-manual-attendance', data),
  deleteAttendanceRecord: (id) => ipcRenderer.invoke('delete-attendance-record', id),
  updateCashier: (data) => ipcRenderer.invoke('update-cashier', data),
  updateWaiter: (data) => ipcRenderer.invoke('update-waiter', data),
  getKitchenOrders: () => ipcRenderer.invoke('get-kitchen-orders'),
  setOrderStatus: (data) => ipcRenderer.invoke('set-order-status', data),
  setOrderStatusByTable: (data) => ipcRenderer.invoke('set-order-status-by-table', data),
  getTvOrders: () => ipcRenderer.invoke('get-tv-orders'),
  onKitchenUpdated: (callback) => {
    ipcRenderer.removeAllListeners('kitchen-updated');
    ipcRenderer.on('kitchen-updated', (_, data) => callback(data));
  },
  getInventoryAuditPrepare: () => ipcRenderer.invoke('get-inventory-audit-prepare'),
  completeInventoryAudit: (data) => ipcRenderer.invoke('complete-inventory-audit', data),
  getInventoryAudits: () => ipcRenderer.invoke('get-inventory-audits'),
  getInventoryAuditDetails: (id) => ipcRenderer.invoke('get-inventory-audit-details', id)
});
